language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - rbx-19mode
#  uncomment this line if your project needs to run something other than `rake`:
before_script: bundle exec rake populate   
script: bundle exec rspec spec
